// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9NTJIxlEnnXyEDSpwhIy0HJ-OOFOM5ng',
    appId: '1:222662073057:web:21a9593361f07456c375a0',
    messagingSenderId: '222662073057',
    projectId: 'streetscape-65968',
    authDomain: 'streetscape-65968.firebaseapp.com',
    storageBucket: 'streetscape-65968.appspot.com',
    measurementId: 'G-DKV2M2FHFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5EVnGm1Ou9xDdX6Oh4Xc4TYRXT8VOT5E',
    appId: '1:222662073057:android:33c7e1f78c6dba80c375a0',
    messagingSenderId: '222662073057',
    projectId: 'streetscape-65968',
    storageBucket: 'streetscape-65968.appspot.com',
  );
}
